# Site settings
title: Kim Blackmore
email: kim.blackmore@me.com
description: > # this means to ignore newlines until "baseurl:"
  My github site holds lots of my practice code, but soon it will also hold the code for 
  my Tech-Life Balance system.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: KimBlackm
github_username:  KimBlackmore

# Build settings
markdown: kramdown
